version: '3'

services:

  db:
    image: "mongo:4.0.14"
    command: mongod
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASS
      - MONGO_INITDB_DATABASE=$DB_NAME
      - MONGO_INITDB_USERNAME=$DB_USER
      - MONGO_INITDB_PASSWORD=$DB_PASS
    env_file:
      - .env
    ports:
      - '${DB_PORT}:27017'
    networks:
      - "db-tier"
    volumes:
      - db-vol:/data/db:cached
      - ./scripts/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh:cached

  client:
    build:
      context: './web'
      dockerfile: Dockerfile.development
    restart: unless-stopped
    volumes:
      - './web:/usr/src/web:cached'
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    ports:
      - "8081:4200"
    depends_on:
      - server

  server:
    build:
      context: './server'
      dockerfile: Dockerfile.development
    command: npm run start:dev
    restart: unless-stopped
    volumes:
      - './server:/usr/src/server:cached'
    environment:
      - NODE_ENV=development
      - DB_HOST=db
    env_file:
      - .env
    ports:
      - "8080:3000"
    depends_on:
      - db
    networks:
      - "db-tier"

networks:
  db-tier:

volumes:
  db-vol:
