version: '3'

services:

  db:
    image: "mongo:4.0.14"
    command: mongod
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASS
      - MONGO_INITDB_DATABASE=$DB_NAME
    env_file:
      - .env
    ports:
      - '${DB_PORT}:27017'
    networks:
      - "db-tier"
    volumes:
      - db-vol:/data/db
      - ./scripts/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh


  client:
    build:
      context: './web'
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DB_HOST=db
    env_file:
      - .env
    ports:
      - "8081:80"
    depends_on:
      - server

  server:
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DB_HOST=db
    env_file:
      - .env
    build: './server'
    ports:
      - "8080:3000"
    depends_on:
      - db
    networks:
      - "db-tier"

networks:
  db-tier:

volumes:
  db-vol: